parameters:
  env(SAML_ENABLED): 'true'

  env(SAML_METADATA_LOCATION): 'https://example.com/saml/metadata'
  env(SAML_SIGN_ON_URL): 'https://example.com/saml2'
  env(SAML_LOGOUT_URL): 'https://example.com/saml2'
  env(SAML_IDP_CERT): '/var/certs/idp.crt'
  env(APP_CERT): '/var/certs/certificate.crt'
  env(APP_KEY)': '/var/certs/certificate.key'

  artifactUrl: 'https://digispoof.demodam.nl/artifact'
  app_cert: '%env(APP_CERT)%'
  app_key: '%env(APP_KEY)%'
  app_x509_cert: '%env(file:APP_CERT)%'
  app_rsa_key: '%env(file:APP_KEY)%'

  saml_x509_cert: '%env(file:SAML_IDP_CERT)%'

  saml_login_url: "%env(SAML_SIGN_ON_URL)%"
  saml_logout_url: "%env(SAML_LOGOUT_URL)%"
  saml_metadata_url: "%env(SAML_METADATA_LOCATION)%"


  saml_enabled: '%env(bool:SAML_ENABLED)%'

saml:
  idp:
    entityId: '%env(SAML_METADATA_LOCATION)%'
    singleSignOnService:
      url: '%env(SAML_SIGN_ON_URL)%'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    singleLogoutService:
      url: '%env(SAML_LOGOUT_URL)%'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    x509cert: '%env(file:SAML_IDP_CERT)%'
  sp:
    entityId: '%env(APP_URL)%/saml'
    assertionConsumerService:
      url: '%env(APP_URL)%/saml/SLO/artifact'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact'
    singleLogoutService:
      url: '%env(APP_URL)%/saml/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    privateKey: '%env(file:APP_KEY)%'
    x509cert: '%env(file:APP_CERT)%'
  # Optional settings
  baseurl: '%env(APP_URL)%'
  strict: false
  debug: true
  security:
    nameIdEncrypted:       false
    authnRequestsSigned:   true
    logoutRequestSigned:   false
    logoutResponseSigned:  false
    wantMessagesSigned:    false
    wantAssertionsSigned:  false
    wantNameIdEncrypted:   false
    requestedAuthnContext:
      - 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport'
    signMetadata: true
    wantXMLValidation: true
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'